### PR TITLE
Separate cli tool

### PR DESCRIPTION
**Pull request by Eleonore9**
- Add a new `:cli`profile to create/run the jar for the CCM demo tool.
- Separate the CCM demo tool by moving `run_models.clj` to a new src directory `src-cli.

### CODE REVIEW

**Comment by acron0** [comment]
Should you update the README with the `with-profile` part? It's not very obvious otherwise

**Comment by Eleonore9** [comment]
@acron0 that's a good point! Although Lora has modified the Readme in the other opened PR so she might have conflicts when I merge this and she rebases her branch.
What's the best way to go?

**Comment by Eleonore9** [comment]
@acron0: I think it's easier to give Lora the right "lein uberjar" command to update on the readme!

**Comment by acron0** [comment]
I'll leave it up to you :shipit:

**Pull request merged**
